- .github/workflows/test.yaml
- README.md
- ape_foundry/__init__.py
- ape_foundry/providers.py
- tests/test_provider.py
- tests/test_transaction.py
Gets Foundry up-and-running!
**Note**: Won't too great until https://github.com/foundry-rs/foundry/issues/1514 and https://github.com/foundry-rs/foundry/issues/1511 are resolved.
* Find links in README
* Remove config-file stuff
* Adjusted `build_command()` implementation
* Adjusted and ensured RPC calls
* Fixed tests
Try to use in your project (eventually)
> feat: foundry

- ape_foundry/providers.py
- tests/test_provider.py
Use params on mine instead of loop.
> fix: use mine parameters correctly

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- ape_foundry/providers.py
- pyproject.toml
- setup.py
> chore: bump ape core 0.4.0

- README.md
> chore: s/node.js/rust

- ape_foundry/providers.py
- setup.py
This is needed as a companion to https://github.com/ApeWorX/ape/pull/1082 since the plugin uses ape's web3 dependency
> fix: update web3 isConnected()

- ape_foundry/providers.py
Port over the logic from https://github.com/ApeWorX/ape-hardhat/commit/cc3337c70c0a24d5b13494bdd2539aca1a19b2ec to fix the PoA issues we're running into
> fix: inject geth PoA middleware if needed

- .github/workflows/test.yaml
- ape_foundry/provider.py
- tests/ape-config.yaml
- tests/conftest.py
- tests/expected_traces.py
- tests/test_fork_provider.py
- tests/test_provider.py
- tests/test_trace.py
* Undoes accidental gas thing we don't
* Fixes a PoA issue that occurred when connecting to an existing network.
* Refactors tests.
> fix: PoA issues when connecting to existing networks

- ape_foundry/provider.py
- tests/test_fork_provider.py
- tests/test_provider.py
> refactor: updates from provider changes as a whole

- ape_foundry/__init__.py
Add support for Optimism and Arbitrum networks
fixes: #
> feat: add optimism and arbitrum network support [APE-619]

- ape_foundry/__init__.py
- ape_foundry/provider.py
- setup.py
- tests/ape-config.yaml
- tests/test_fork_provider.py
Was going to do the same as https://github.com/ApeWorX/ape-hardhat/pull/133 but noticed polygon was even supported yet, so we got a 2fer
> feat: support Polygon networks [APE-790]

- ape_foundry/provider.py
Later feedback for perf on poa checking
> perf: save a request when setting PoA middleware [APE-793]

- ape_foundry/provider.py
- setup.py
- tests/test_provider.py
requires https://github.com/ApeWorX/ape/pull/1397/files
updates how gas is tracked
will help make coverage stuff in the end
> refactor: updates we can do because of 0.6.9 [APE-877]

- .github/workflows/test.yaml
- README.md
- pyproject.toml
> feat: python 3.11  [APE-1041]

- ape_foundry/provider.py
> refactor: swap `hexbytes.HexBytes` with `ethpm_types.HexBytes`

- tests/test_gas_report.py
> test: fixes from ctor in traces work

- ape_foundry/provider.py
- tests/test_provider.py
requires https://github.com/ApeWorX/ape/pull/1455
> fix: passing along base err [APE-986]

- ape_foundry/provider.py
- ape_foundry/utils.py
- tests/test_provider.py
should be compatible with https://github.com/ApeWorX/ape/pull/1484, but not required to merge
> feat: add `set_storage` [APE-1093]

- ape_foundry/provider.py
- setup.py
- tests/test_pytest.py
Allows coverage to be tracked on calls.
> feat: track coverage on calls [APE-1026]

- ape_foundry/provider.py
gas price is a string for some reason now in web3, seems like a bug because it is described as an int.
Anyway, we fixed this in core already but it isn't released yet so we have to temporarily fix here as well
check if str and hex and int 16 it
passing tests
will need this for the other 2 PRs
> fix: gas price hack fix [APE-1199]

- ape_foundry/provider.py
- tests/conftest.py
- tests/test_provider.py
fixes: #61 
Fixes: APE-1190
* Only start local process if the host is a localhost
* return empty list for `build_command()` if using localhost
this one may require some manual testing - there isn't really any remote testing we can do in CI
> fix: issues demanding anvil bin [APE-1190]

- README.md
- ape_foundry/provider.py
- tests/test_provider.py
> feat: connect to remote host using environment variable [APE-1202]

- .pre-commit-config.yaml
- ape_foundry/provider.py
- setup.py
- tests/ape-config.yaml
- tests/test_fork_provider.py
- tests/test_provider.py
* Makes use of adhoc provider settings
* Makes use of new fork upstream provider tools
> feat: upgrade to Ape 0.6.24 [APE-1461]

- ape_foundry/provider.py
- tests/conftest.py
- tests/test_fork_provider.py
- tests/test_provider.py
fixes: #81 
so couple things,
there seems to be an issue with `eth_gasPrice` not honoring the CLI value, so had to throw in a hack for that.
but mainly, the fixes i put in place to help wavey ended up breaking some remote node stuff... sorry.
use RPC whenever we can.
actually need @mikeshultz to verify if this fixes the issue.
i know it at least fixes _issues_ would like to make sure.
**i made sure wavey's project still works!**
> fix: handling gas-related fixes for remote nodes

- tests/test_provider.py
- tests/test_pytest.py
Fixes test checking `provider.base_fee` after setting `base_fee` in config.
fixes: #94
> fix(test): anvil behavior changed with --block-base-fee-per-gas

- ape_foundry/__init__.py
> feat: declare base and blast support

- ape_foundry/__init__.py
fixes: #
~~- [ ] New test cases have been added and are passing~~
~~- [ ] Documentation has been updated~~
> feat(fork): add sepolia support for L2 networks

- ape_foundry/provider.py
logically no fix in the end but fixes something earlier on in the execution by using the correct default message.
> fix: variable was not used

- ape_foundry/provider.py
Delete log line because it happens already from Core. (added here: https://github.com/ApeWorX/ape/pull/1930)
fixes: https://github.com/ApeWorX/ape/issues/1956
delete line
> chore: delete double log (is happening in core)

- .pre-commit-config.yaml
- ape_foundry/provider.py
- setup.py
- tests/test_provider.py
> feat: support `raise_on_revert` flag for calls and transactions

- ape_foundry/provider.py
- setup.py
can delete hacky fix after https://github.com/ApeWorX/ape/pull/2210 merges and releases
> fix: delete unneeded try / except blocks for erroring revert checks on emptiness

- .pre-commit-config.yaml
- ape_foundry/__init__.py
- ape_foundry/provider.py
- setup.cfg
- setup.py
before:
```
In [1]: %time import ape_foundry
CPU times: user 1.87 s, sys: 219 ms, total: 2.09 s
Wall time: 2.23 s
```
after:
```
%time import ape_foundry
CPU times: user 8.19 ms, sys: 3.58 ms, total: 11.8 ms
Wall time: 12 ms
```
> perf: make plugin load faster

- .github/workflows/docs.yaml
- CONTRIBUTING.md
- ape_foundry/provider.py
- docs/conf.py
- docs/index.rst
- docs/userguides/quickstart.md
- setup.py
> feat: support web3.py dependencies

- ape_foundry/provider.py
- ape_foundry/trace.py
- tests/test_provider.py
should make return value faster... testing still WIP
> perf: get faster `.return_value` from traces
