ApeWorX/ape-foundry

README.md, ape_foundry/constants.py, ape_foundry/providers.py
- allow specifying `evm_version` in fork config
- automatically choose the correct fork if a block number is specified
- add `ecosystem:network:start_block:evm_version` mapping
- hardcode block to fork mapping for ethereum mainnet
- guess version from upsteam provider if block is provided but evm version is not provided, providing less surprising behavior when forking from older blocks
- add a `--hardfork` argument to `anvil` if we run something other than the latest fork
fork from an old block
- [foundry hardfork options](https://github.com/foundry-rs/foundry/blob/03b6f2c458634859ee1c35bbcb74f0dff75f27e1/anvil/src/config.rs#L676-L687)
- [erigon chain specs](https://github.com/ledgerwatch/erigon/tree/devel/params/chainspecs)
=> feat: detect evm version when forking from a certain height

ape_foundry/providers.py, tests/test_provider.py
Added `raise_on_fail` per https://github.com/ApeWorX/ape/pull/957
Added new test to verify
=> feat!: add raise_on_fail to send_transaction()

ape_foundry/provider.py, tests/test_fork_provider.py, tests/test_provider.py
* Fixes situation where `ContractLogicError` would not raise when a txn reverted
* Fixes issue with hex-strs as txn-type
=> fix: issue with detecting `ContractLogicError` from impersonated accounts

ape_foundry/provider.py, setup.py, tests/test_fork_provider.py
fixes: #31 
After resetting fork to `block_number`, added call to `anvil_setNextBlockBaseFeePerGas` endpoint with `base_fee` of new forked chain state.
=> fix: reset fork base fee

ape_foundry/provider.py, tests/ape-config.yaml
Makes faster and less buggy by using the new `debug_traceCall`
Note: you may need to do a `foundryup`.
mostly copy `ape-geth` but had to change 1 small thing to make RPC happy.
Gas reports work as they did before!
Also if you had issues before, maybe you don't now??
=> refactor: use debug_traceCall

ape_foundry/provider.py, tests/test_provider.py
We hadn't implemented the `geth` style traces yet in this plugin.
They are needed for coverage and other features to work, so this implements the necessary API method.
Copy `ape-hardhat`
Also needed to add a new flag to the CLI startup.
Works the same as `geth` and `hardhat` now.
=> feat: implement `get_transaction_trace()` [APE-750]

ape_foundry/provider.py
=> fix: issue causing web3.py 6.0 to fail [APE-766]

ape_foundry/provider.py, setup.py
for when after https://github.com/ApeWorX/ape/pull/1361 releases
=> fix: del unneeded code after web3 6 [APE-768]

ape_foundry/provider.py
noticed we were raising when we should have been returning.
all it affects is the location of the exception, so not much, but is weird when looking at internal stack frames otherwise.
`raise` -> `return`
=> fix: return exception instead of raise in `get_virtual_machine_error()` [APE-796]

README.md, ape_foundry/exceptions.py
error message was poorly copied from `ape-hardhat` and it is not true for `ape-foundry`
=> docs: correct misleading error message [APE-897]

README.md, ape_foundry/provider.py, setup.py, tests/conftest.py, tests/test_fork_provider.py, tests/test_provider.py
Allows specifying a host for connecting remotely to an anvil node.
When the user puts `host`, use that instead of launching the process.
Basically, works the same except it won't try to launch anything; it will only try to connect.
`port` field will trigger deprecation warning
=> feat: allow connecting to remote anvil nodes [APE-892]

.github/workflows/commitlint.yaml, .github/workflows/prtitle.yaml, .github/workflows/publish.yaml, .github/workflows/test.yaml, README.md, ape_foundry/provider.py, setup.py, tests/ape-config.yaml, tests/conftest.py, tests/test_provider.py, tests/test_trace.py
Noticed that `ape-hardhat` uses both `base_fee` and `priority_fee` values of `0`, which allows being able to use any account you want as an impersonated account, regardless of how much funds it has.
`ape-foundry` differs here. Instead, it defaults to having values returned for each field.
**We can discuss if we want to conform one or the other to the same (0.7 ?) or if it is ok to have them be different.**
But for now, to allow them to work the same if desired, allow configuring these fields.
* Add options to foundry config
* Honor options respectively
* Add test
Create an use a config like:
```yaml
foundry:
priority_fee: 0
base_fee: 0
```
then crack open a console:
```bash
ape console --network ethereum:local:foundry
```
then check that it is set:
```python
In [1]: …
```
=> feat: allow configuring `base_fee` and `priority_fee` [APE-847]

ape_foundry/provider.py, tests/test_provider.py
some weird issue where base fee is not in the block.
thankfully, in foundry this is ok because we configure the base fee ahead of time and just return that value, so it is also a performance optimization in that sense.
=> fix: base fee not found in block err [APE-1021]

ape_foundry/provider.py, tests/test_provider.py
add anvil's `get_autoMine` call so you can tell what kind of behavior your anvil done is up to. reference: <https://book.getfoundry.sh/reference/anvil/>
added this code:
```py
def get_auto_mine(self) -> bool:
return self._make_request("anvil_getAutoMine", [])
```
install the plugin, connect to an anvil node, and run `provider.get_auto_mine()`.
using `anvil` default:
```py
print(f"{provider.get_auto_mine()=}")
provider.get_auto_mine()=True
```
with `anvil --block-time 1` that mines a new block every 1 second... automatically?
```py
print(f"{provider.get_auto_mine()=}")
provider.get_auto_mine()=False
```
=> feat: add get_auto_mine function [APE-998]

ape_foundry/provider.py, tests/test_provider.py
Noticed that remote node `uri` did not connect to the right port if it did not begin with `http` or `https` so made sure that it would still work if it was missing in the `config`. 
fixes: #
Set the host in the `ape-config.yaml` in one project and check the `network.provider.uri` in the ape console. Then go into a second project with the same config and check to see that the ape console can connect to the first.
=> fix: remote node check [APE-1110]

ape_foundry/provider.py, tests/test_provider.py
allows setting automine via `provider.auto_mine = True`
=> feat: set automine [APE-1173]

README.md, ape_foundry/provider.py, tests/test_provider.py
adds config options `auto_mine` and `block_time` to allow controlling mining more of your node
=> feat: mining config options like block time auto-mine [APE-1175]

ape_foundry/provider.py
issue preventing base fee from being correct when connecting to a remote host
remove "perf"
send txns on remote host and notice base fee is no longer 0 when it makes sense
=> fix: base fee fix for remote host [APE-1196]

.pre-commit-config.yaml, ape_foundry/provider.py, setup.py, tests/test_provider.py
This helps dev messages, coverage, and anything needing source tracing to work better when failures occur on calls (view methods)
in error handling, try make the source tb and then set it.
Note, I had to do this in ape-geth to fix an issue with dev message detection so am copying the changes here.
Unable to test this very easily as it also requires ape-vyper. hmmmmm.
=> fix: pre-set source traceback on traced calls [APE-1325]

ape_foundry/constants.py
took block numbers from here
https://github.com/ethereum/execution-specs
=> fix: detect paris and shanghai evm based on chain height [APE-1359]

ape_foundry/provider.py, tests/test_fork_provider.py
=> feat: add http_uri and ws_uri [APE-1447]

ape_foundry/provider.py
`anvil` finally added the `anvil_mine` method (mimicking [`hardhat_mine`](https://github.com/ApeWorX/ape-hardhat/blob/main/ape_hardhat/provider.py#L707C61-L707C61)) so I copy-pasted that implemention to `anvil` call
~~- [ ] New test cases have been added and are passing~~
~~- [ ] Documentation has been updated~~
=> refactor: use `anvil_mine` instead of `evm_mine`

ape_foundry/provider.py, setup.py, tests/conftest.py, tests/test_provider.py
same as core PR: https://github.com/ApeWorX/ape/pull/1788
=> fix: issue where would not get a transaction error when expected

.pre-commit-config.yaml, ape_foundry/provider.py, setup.py, tests/test_provider.py
* fix: issue with static-fee txns where impersonated accounts failed without balance
* fix: issue where transactions state was lost for proxy-based accounts
* fix: forked config attr error
* fix: issue with 
* fix: issue where we would reset the fork to a problematic base fee
fixes: https://github.com/ApeWorX/ape/issues/1783
1: set gas price in CLI to default to 0
2: delete hack in code that is no longer necessary (at least I think it is no longer necessary??)
- So i am referring to the `set_code(0)` part for impersonated contracts we were doing... we had to do that before but it seems we no longer need to? also it seems to cause problems... (one of many, unfortunately)
3: set `self._fork_config.upstream_provider = upstream_name`
4: delete the part in reset fork where we do …
=> fix: various issues preventing impersonated accounts and forks from working

ape_foundry/provider.py, tests/test_provider.py
<!-- The `fixes:` field denotes an issue that will be marked resolved by merging this PR -
=> feat: allow configuring `disable_block_gas_limit`

ape_foundry/provider.py, tests/test_provider.py
1. issue where if receipt is used as txn, getting the hash would fail silently.
1. convert the hash to str in both conditions (str or bytes)
=> fix: custom error check fails when error has receipt instead of transaction

ape_foundry/provider.py
Will show the call trace on transaction revert.
Ref: https://github.com/ApeWorX/ape/issues/1945
=> feat: show call trace on transaction revert

.github/workflows/codeql.yml, .github/workflows/commitlint.yaml, .github/workflows/prtitle.yaml, .github/workflows/publish.yaml, .github/workflows/test.yaml, .pre-commit-config.yaml, README.md, pyproject.toml, setup.py
=> feat: python 3.12 support

.pre-commit-config.yaml, ape_foundry/__init__.py, ape_foundry/constants.py, setup.py, tests/ape-config.yaml, tests/conftest.py, tests/test_fork_provider.py, tests/test_provider.py, tests/test_trace.py
https://blog.ethereum.org/2023/11/30/goerli-lts-update
https://www.alchemy.com/blog/goerli-faucet-deprecation
Goerli support on all networks is ending soon:
- February 16th - [Base Goerli](https://www.alchemy.com/blog/base-goerli-testnet-deprecation)
- March 7th - [Optimism Goerli](https://www.alchemy.com/blog/optimism-goerli-testnet-deprecation)
- March 18th - [Arbitrum Goerli](https://www.alchemy.com/blog/arbitrum-goerli-testnet-deprecation)
- April 1st - [Ethereum Goerli](https://www.alchemy.com/blog/ethereum-goerli-testnet-deprecation)
- April 6th - [Polygon zkEVM Goerli](https://www.alchemy.com/blog/polygon-zkevm-cardona-is-live)
- April 11th - [Starknet Goerli](https://www.alchemy.com/blog/starknet-sepolia-is-live)
- April 13th - [Polygon …
=> refactor: remove goerli

.github/workflows/test.yaml, .pre-commit-config.yaml, README.md, ape-config.yaml, ape_foundry/constants.py, ape_foundry/provider.py, pyproject.toml, setup.py, tests/conftest.py, tests/expected_traces.py, tests/test_fork_provider.py, tests/test_provider.py, tests/test_trace.py
=> feat!: 0.8 support

ape-config.yaml, ape_foundry/provider.py, setup.py, tests/test_fork_provider.py, tests/test_provider.py
support and honor the `--balance` flag via test config balance, requires this PR: https://github.com/ApeWorX/ape/pull/2173
set the initial balance from the value from the config, behaves like other testing providers.
=> feat: honor `balance` test config value

README.md, ape_foundry/provider.py, tests/test_provider.py
somehow this was missing! it was on forks but not the regular local one.
=> feat: allow setting `evm-version` in local network

README.md, ape_foundry/provider.py, tests/test_provider.py
=> feat: global evm-version config

ape_foundry/provider.py, tests/test_provider.py
fixes: #97 
This fixes what went wrong but i am not sure about the actual problem enough to know how to test this OR ensure everything else work
=> fix: issue detecting proper message from certain virtual machine errors

.pre-commit-config.yaml, ape_foundry/provider.py, setup.cfg, setup.py, tests/test_provider.py
* feat: Add a config to set the `--optimism` flag (or turn it off in cases when we turn it on automatically)
* feat: when using Optimism based networks, automatically pass `--optimism` (unless specified not to)
=> feat: set --optimism flag for optimism-based networks

.pre-commit-config.yaml, ape_foundry/provider.py, setup.py, tests/expected_traces.py
mostly getting to delete code because of this work here: https://github.com/ApeWorX/ape/pull/2195
=> refactor: utilize core feature for impersonating accounts and sending txns

ape_foundry/provider.py, setup.py, tests/test_performance.py
Before:
```
Wall time: 554 ms
```
Then with https://github.com/ApeWorX/ape/pull/2211
```
Wall time: 450 ms
```
Then with this PR and not https://github.com/ApeWorX/ape/pull/2211
```
Wall time: 273 ms
```
Then with this PR AND https://github.com/ApeWorX/ape/pull/2211
```
Wall time: 245 ms
```
I think the main thing was not defining such a large method within another method
but also some condition combines probably helped.
should work like it did before
=> perf: optimize getting virtual machine errors

ape-config.yaml, ape_foundry/provider.py, tests/expected_traces.py, tests/test_fork_provider.py, tests/test_provider.py, tests/test_trace.py
`set_storage()` was failing with improper hex strings.
I noticed in ape-safe, is the reason we had the failing tests there
I had to enable the ape framework's stack traces tho, which is kinda weird.
use to_hex instead of hex
tests pass
=> fix: issues with web3 v7 / hex strings missing 0x prefix

ape_foundry/provider.py, tests/test_provider.py
=> fix: some reverts tests were failing because of a sudden reverts prefix on error messages
